export type {
  AdminConfig,
  ActivityItem,
  ActivityItemSource,
  AgentReadingEvent,
  ApiError,
  AuthUser,
  ChangesSinceResponse,
  CommitProposalResponse,
  ContentCommittedEvent,
  CreateProposalRequest,
  CreateProposalResponse,
  DirtyChangedEvent,
  DirtyDocument,
  DirtySection,
  DocPath,
  DocStructureChangedEvent,
  DocStructureNode,
  DocumentTreeEntry,
  EvaluatedSection,
  GetActivityResponse,
  GetAdminSnapshotHealthResponse,
  GetDocumentResponse,
  GetDocumentSectionsResponse,
  GetDocumentsTreeResponse,
  GetHeatmapResponse,
  HeadingPath,
  HeatmapEntry,
  HumanInvolvementPreset,
  HumanHumanInvolvementPresetName,
  ListProposalsResponse,
  LoginProvider,
  PresenceDoneEvent,
  PresenceEditingEvent,
  Proposal,
  ProposalFile,
  ProposalId,

  ProposalHumanInvolvementEvaluation,
  ProposalSection,
  ProposalStatus,
  PublishRequest,
  PublishResponse,
  ReadDocStructureResponse,
  ReadProposalResponse,
  ReadSectionResponse,
  SectionMeta,
  SectionScoreSnapshot,
  SectionState,
  SectionTargetRef,
  SectionVerdict,
  BatchVerdict,
  SessionInfoResponse,
  UpdateProposalRequest,
  WithdrawProposalResponse,
  WriterDirtyState,
  WriterIdentity,
  WriterType,
  WsClientMessage,
  WsServerEvent,
} from "../../../sharedlibs/shared-types/src/index.js";

export {
  HUMAN_INVOLVEMENT_PRESETS,
  sectionHeadingKey,
  sectionGlobalKey,
  sectionFragmentKey,
} from "../../../sharedlibs/shared-types/src/index.js";
