export const userFeatures = [
  "Edit any section of a document by clicking into it; only the section you're focused on loads a full editor — other sections show as read-only previews",
  "Arrow-key navigation moves seamlessly between sections — up from the top of one section goes to the bottom of the one above",
  "Copy text across multiple sections produces clean markdown without UI clutter",
  "See other humans' cursors and selections in real time when multiple people edit the same document",
  "Other humans can watch you edit a section in real time even if they aren't editing it themselves",
  "All docs and folders available on disk in pure .md Markdown format for readonly access by 3rd party tools (/snapshots)",
  "Per-section save indicators: blue dot for unsaved local changes, amber while saving to server, green once confirmed on disk",
  "Connection status banners: yellow while reconnecting, red if connection is lost entirely",
  "Aggregate save status indicator: 'N unsaved sections', 'N sections waiting for confirmation', 'All changes saved', or 'Up to date'",
  "Deleted sections show an amber placeholder with struck-through heading until the server confirms deletion",
  "Editing sessions auto-end after 60 seconds of inactivity — your changes are saved and published automatically",
  "Floating Mirror panel shows all your unpublished changes across all documents, with per-document 'Publish Now' and a global 'Publish All Docs' button",
  "The Mirror panel appears automatically when you have unpublished changes and hides when you have none",
  "Changes are automatically saved and published when you close the tab, navigate away, or go idle — the Mirror panel is optional",
  "Version history shows human-friendly entries like 'Alice — doc-a.md [Pricing, Executive Summary]' with optional AI-generated summaries",
  "The UI uses 'Publish' as the only term for saving to permanent history — no technical terms like 'commit' are exposed",
  "Create a Proposal to reserve sections for extended work without being interrupted by idle timeouts",
  "In proposal mode, any section you edit is automatically added to your proposal — no need to manually select sections in advance",
  "Sections reserved via a proposal are locked for other users (both humans and agents) — others see 'Reserved by [name]' and read-only content",
  "Your proposal shows as a floating box listing all documents and sections in it, with a description field, Publish, and Cancel buttons",
  "Publishing a proposal saves all reserved sections to permanent history at once; cancelling discards all changes and releases locks",
  "One active proposal per user at a time",
  "Sections in your proposal show a colored border so you can see what's part of your proposal while editing",
  "Subtle time-decaying 'Agent reading' indicator appears on a section when an AI agent is looking at it",
  "When an AI agent has submitted changes to a section you're viewing, you see a notice like 'Agent wants to modify this section (waiting)'",
  "After agent changes are accepted, you see attribution like 'Modified by writer-bot, 2h ago. Intent: Updated market data'",
  "When changes are published to a section you're viewing, it briefly highlights with a pastel background and shows 'Updated by [name]'",
  "Agents cannot directly change published content — they must submit proposals that the system evaluates before accepting",
  "The system protects recent human work from agent overwrites: the more recently you edited, the harder it is for an agent to change it",
  "Admin posture slider controls how aggressively agents can overwrite human work, with four presets from YOLO (30s) to Conservative (8h)",
  "Each posture setting has a plain-language explanation of its implications",
  "Admin heatmap page shows a live system-wide view of how protected every section is, refreshing every 5-10 seconds",
  "Agents providing a per-section justification get a small bonus toward acceptance — matters more in conservative environments",
  "Long sections without sub-headings show a warning encouraging the author to break them up",
  "Documents can have deeply nested heading structures — sub-headings are automatically reorganized without losing content",
  "If the server crashes, at most ~2 seconds of your most recent typing is lost; everything else recovers automatically on restart",
  "Page reloads always show your latest saved content, not stale published content",
  "Large documents show a loading indicator with size estimate and a suggestion to break into smaller files",
  "The system never requires you to take any action to protect your work — publishing is optional, changes are always preserved",
  "Full drag/drop support for reordering and relocating section titles and bodies",
  "Agent simulator page shows agents what level of protection they'd face when proposing changes",
    "Drag sections to reorder them or move content between sections — a colored border previews the drop target, and drops are blocked if someone else is editing there",
  "Version history panel lists past versions of a document with author, timestamp, and message — click any version to preview its full text or restore the document to that point",
  "Restoring a previous version goes through the same proposal system as any other change — locked sections are respected and nothing is silently overwritten",
  "If the server crashes while you're editing, your work reappears automatically as a 'Recovered edits' section at the bottom of the document, ready to review and relocate",
  "Switch between Standard and Governance view using a toggle in the toolbar — or admins can force Governance mode for everyone",
  "Governance view adds a left column showing each section's human-involvement score, agent permission tier (Blocked, Gated, or Auto), and a checklist of what agents can and can't do",
  "Governance view adds a right column with a chronological audit trail per section — who changed it, when, human or agent, and any justification provided",
  "Agent permission tiers are computed automatically from how recently humans edited: heavily-edited sections block agents, moderately-edited sections gate certain actions, untouched sections allow full autonomy",
  "AI agents connect through capability tiers — from simple file reads up to full proposal-based collaboration with human-involvement checks",
  "The agent setup page detects your AI tool (Claude Code or Cursor) and shows tool-specific configuration with one-click copy",
     "Per-line human/AI authorship coloring in governance view shows who wrote each line",
  "Sidebar  updates automatically when other users create, delete, or rename documents",
  "Admin permissions page lets admins manage roles, per-document access, and custom roles from the UI",
  "Documents can be restricted to specific user roles (e.g. 'legal-team', 'board-members')",
  "Server shows a friendly 'starting up' screen during crash recovery instead of broken pages",
  "Sign in via your organization's SSO provider (OIDC) — no passwords stored",
  "First admin is bootstrapped via a one-time code printed to the server console"
];

export const architectureFeatures = [
  "All content stored as plain markdown files on disk — no database. Entire system state can be inspected by listing directories and reading files",
  "Documents split into section files referenced by skeleton files with {{section: filename.md}} markers — allows overwriting a single section without touching the rest",
  "Skeleton files can nest: a section file can itself be a skeleton with its own sub-sections, mirroring heading hierarchies",
  "When a section gains sub-headings, its file is automatically restructured into a sub-skeleton with the original body preserved",
  "Git is the version history. Every publish or auto-save is a git commit. No separate history mechanism — git log is the audit trail",
  "Proposal lifecycle state is determined by filesystem directory (draft/, pending/, committing/, committed/, withdrawn/). State transitions are file moves",
  "Three directories tell you everything: content/ (published), sessions/ (in-flight edits), proposals/ (agent and human proposals)",
  "Editing sessions use per-document Y.js CRDT with one Y.XmlFragment per section — one WebSocket connection covers all sections",
  "The CRDT is a transport layer, not storage. Y.Doc instances exist only in memory while someone is connected; reconstructed from files on reconnect",
  "Session data is written to disk as raw fragments (every 1-2s for crash safety) and canonical-ready files (clean, structurally valid)",
  "Canonical-ready session files use the same skeleton + section structure as published content — same code paths read both",
  "Structural normalization only runs when the user leaves a section, never during editing. The person who causes a structural change never experiences disruption",
  "All normalization is event-driven (focus change, disconnect, publish), never timer-driven. No periodic sweeps or speculative restructuring",
  "Every commit is triggered by a concrete event: idle 60s, disconnect, Publish click, server shutdown, or crash recovery",
  "Content flush (to disk every 1-2s) and commit (to permanent history) are separate operations. Flushing is constant; committing is event-driven",
  "Crash-safety data loss window is ~2 seconds. On recovery: read raw fragments, normalize, commit under a 'crash recovery' identity",
  "Per-user attribution tracked in lightweight author metadata files — no content, just references. Powers the Mirror panel and survives restarts",
  "When one user publishes, all other users who edited a section get co-attribution for those sections",
  "Danger/protection score is a pure function of time-since-last-human-edit, computed fresh on every API request — never stored or cached",
  "Time since last human edit derived from raw fragment mtime, canonical session mtime, or last human git commit timestamp",
  "Danger function is a sigmoid curve. Admin presets only change midpoint and steepness parameters — all other behavior stays the same",
  "Blocking threshold is 0.5. Agent justification reduces score by 0.1 — worth more wall-clock time in conservative presets than aggressive ones",
  "Agent proposals always start in draft state. The agent must explicitly request commit as a separate step (create, then commit)",
  "One draft proposal per writer. Submitting a new one returns an error, or use replace=true to auto-withdraw the old one",
  "Asymmetric treatment: human work is protected by the danger system; agent-to-agent overwrites are last-committed-wins with no protection",
  "REST API overlays dirty session content on published canonical content — page reloads always show the latest saved state",
  "Real-time editing via CRDT WebSocket only. REST sections endpoint is for page loads and refreshes, never polled for live updates",
  "Agent-reading detection requires zero agent cooperation — the server intercepts API read calls and broadcasts presence events automatically",
  "DocumentSkeleton class is the single canonical source of section identity, heading paths, file paths, and tree structure",
  "Milkdown (ProseMirror) uses Y.js sync in normal mode; in proposal mode runs standalone with its own state, saving to proposal files",
  "Y.js Awareness shared across all section editors via a single Awareness instance per document",
  "Two WebSocket channels: binary per-document CRDT for editing data, and JSON presence hub for system-wide events",
  "Human and agent proposals use the same infrastructure, same commit path, same API endpoints — distinguished only by writer.type",
  "Sections in a pending human proposal are hard-blocked for everyone else, even after the CRDT session has committed",
  "Agent MCP access has three tiers: Tier 1 (file operations), Tier 2 (+ intent declaration), Tier 3 (full proposal workflow with danger-score checks). Claude Code and Cursor auto-detect to Tier 3",
  "Crash recovery reads raw session fragments from disk, layers them on the last committed state, and appends unmatched content as a recovery section — no special UI or user interaction required",
  "Version restore creates a proposal through the same pipeline as human and agent proposals, inheriting all lock and danger-score checks — git show provides the historical content",
];
